"""Ajout des champs manquants au modèle Client

Revision ID: 2c75ec31be68
Revises: 
Create Date: 2025-07-10 22:25:35.122705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c75ec31be68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_naissance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_modification', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('date_modification')
        batch_op.drop_column('preferences')
        batch_op.drop_column('profession')
        batch_op.drop_column('date_naissance')

    # ### end Alembic commands ###
